version: "3"

services:

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbit-automobile
        environment:
            RABBITMQ_DEFAULT_USER: "automobile"
            RABBITMQ_DEFAULT_PASS: "automobile"
        ports:
            - 5672:5672
            - 15672:15672

    sql-server:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: automobile-sql-server
        build: 
            context: ../sql
            dockerfile: ./Dockerfile
        environment:
            SA_PASSWORD: "AutoM@123"
            ACCEPT_EULA: "Y"     

    web-mvc:
        image: automobile-web-mvc:latest
        #container_name: automobile-web-mvc
        build:
            context: ../src
            dockerfile: ./web/Automobile.MVC/Dockerfile
        restart: always            
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://*:5001
        volumes: 
            - dpkeys:/var/data_protection_keys/         
        depends_on:
            - api-automobile

    api-automobile:
        image: automobile-api:latest
        container_name: automobile-api
        build: 
            context: ../src
            dockerfile: ./services/Automobile.API/Dockerfile      
        restart: always             
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:5201;http://+5202
            - ASPNETCORE_Kestrel__Certificates__Default__Password=automobile
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/automobile-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - sql-server         

    automobile-server:
        image: automobile-server:latest
        container_name: automobile-server    
        build: 
            context: ./
            dockerfile: ./nginx/Dockerfile 
        restart: always 
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - web-mvc

volumes:
    dpkeys:     