// <auto-generated />
using System;
using Automobile.Infra.EF.Configurations.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Automobile.Infra.EF.Migrations
{
    [DbContext(typeof(AutomobileContext))]
    [Migration("20220329004002_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Automobile.Domain.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("ProprietarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProprietarioId")
                        .IsUnique();

                    b.ToTable("ProprietarioEnderecos");
                });

            modelBuilder.Entity("Automobile.Domain.Entities.Modelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnoFabricacao")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AnoModelo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId")
                        .IsUnique();

                    b.ToTable("Modelos");
                });

            modelBuilder.Entity("Automobile.Domain.Entities.Proprietario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Cancelado")
                        .HasColumnType("SMALLINT");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Proprietarios");
                });

            modelBuilder.Entity("Automobile.Domain.Entities.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MarcaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProprietarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quilometragem")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("Renavam")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<short>("Status")
                        .HasColumnType("SMALLINT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId")
                        .IsUnique();

                    b.HasIndex("ProprietarioId")
                        .IsUnique();

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("Automobile.Domain.Entitites.Marca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Cancelado")
                        .HasColumnType("SMALLINT");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("Automobile.Domain.Entities.Endereco", b =>
                {
                    b.HasOne("Automobile.Domain.Entities.Proprietario", "Proprietario")
                        .WithOne("Endereco")
                        .HasForeignKey("Automobile.Domain.Entities.Endereco", "ProprietarioId")
                        .IsRequired();

                    b.Navigation("Proprietario");
                });

            modelBuilder.Entity("Automobile.Domain.Entities.Modelo", b =>
                {
                    b.HasOne("Automobile.Domain.Entities.Veiculo", "Veiculo")
                        .WithOne("Modelo")
                        .HasForeignKey("Automobile.Domain.Entities.Modelo", "VeiculoId")
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Automobile.Domain.Entities.Proprietario", b =>
                {
                    b.OwnsOne("Automobile.Domain.Entities.Objects.Documento", "Documento", b1 =>
                        {
                            b1.Property<Guid>("ProprietarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("NumeroDocumento")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("varchar(14)")
                                .HasColumnName("NumeroDocumento");

                            b1.Property<short>("TipoDocumento")
                                .HasColumnType("SMALLINT")
                                .HasColumnName("TipoDocumento");

                            b1.HasKey("ProprietarioId");

                            b1.ToTable("Proprietarios");

                            b1.WithOwner()
                                .HasForeignKey("ProprietarioId");
                        });

                    b.OwnsOne("Automobile.Domain.Entities.Objects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ProprietarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasColumnType("varchar(254)")
                                .HasColumnName("Email");

                            b1.HasKey("ProprietarioId");

                            b1.ToTable("Proprietarios");

                            b1.WithOwner()
                                .HasForeignKey("ProprietarioId");
                        });

                    b.Navigation("Documento");

                    b.Navigation("Email");
                });

            modelBuilder.Entity("Automobile.Domain.Entities.Veiculo", b =>
                {
                    b.HasOne("Automobile.Domain.Entitites.Marca", "Marca")
                        .WithOne("Veiculo")
                        .HasForeignKey("Automobile.Domain.Entities.Veiculo", "MarcaId")
                        .IsRequired();

                    b.HasOne("Automobile.Domain.Entities.Proprietario", "Proprietario")
                        .WithOne("Veiculo")
                        .HasForeignKey("Automobile.Domain.Entities.Veiculo", "ProprietarioId")
                        .IsRequired();

                    b.Navigation("Marca");

                    b.Navigation("Proprietario");
                });

            modelBuilder.Entity("Automobile.Domain.Entities.Proprietario", b =>
                {
                    b.Navigation("Endereco");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Automobile.Domain.Entities.Veiculo", b =>
                {
                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("Automobile.Domain.Entitites.Marca", b =>
                {
                    b.Navigation("Veiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
